### ISSUE TITLE
hi,what's wrong with the code?

### ISSUE THREAD

**Issue by rectinajh** [opporty-com/Plasma-Cash#17]
<img width="1280" alt="2018-08-07 6 02 16" src="https://user-images.githubusercontent.com/3462559/43769352-19e50b3c-9a6c-11e8-9803-6c6876cf9601.png">

**Comment by genisgetman** [comment]
This error is obtained when the version of solidity in contracts and the version of compiler do not match. We will update this soon in our contracts, but if you want to resolve this error now, you need to lower your version of compiller.
